---

tomcat8_source: https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.32/bin/apache-tomcat-8.0.32.tar.gz

tomcat8_pkg: apache-tomcat-8.0.32.tar.gz

tomcat8_pkg1: /tomcat/apache-tomcat-8.0.32.tar.gz

jenkins_pkg: http://mirrors.jenkins.io/war/latest/jenkins.war

tomcat_source: /tomcat

CONFIG_DIR: roles/tomcat/files

CATALINA_HOME: /tomcat

